import {allowedRhythms,getFindings,imageMap} from './data.mjs';
import {ids,missions,deck,fresh,normalize,record} from './core.mjs';
const $=s=>document.querySelector(s),app=$('#app'),KEY='ecg-challenge-v2';
const r=id=>allowedRhythms.find(x=>x.id===id);
const image=id=>`assets/ecg-approved/${imageMap[id]}.png`;
let save=fresh(),level='intermediate',demo=false,view='home',run=null,streak=0,animation=null;
try{save=normalize(JSON.parse(localStorage.getItem(KEY)||'null'));level=['beginner','intermediate','advanced'].includes(localStorage.getItem(KEY+'-level'))?localStorage.getItem(KEY+'-level'):'intermediate';}catch{notice('此瀏覽器暫時無法讀取學習紀錄，本次仍可練習。');}
function notice(s){$('#notice').hidden=false;$('#notice').textContent=s;}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(save));localStorage.setItem(KEY+'-level',level);}catch{notice('學習紀錄暫時無法儲存，關閉頁面後可能遺失。');}$('#xp').textContent=save.xp+' XP';}
function stop(){animation?.cancel();animation=null;}
function navigate(next){stop();view=next;document.querySelectorAll('[data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===next);if(b.dataset.view===next)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});if(next==='home')home();if(next==='report')report();if(next==='settings')settings();window.scrollTo(0,0);app.focus({preventScroll:true});}
function bind(id,fn){$(id).onclick=fn;}
function home(){
 const attempts=Object.values(save.stats).reduce((a,s)=>a+s.seen,0),right=Object.values(save.stats).reduce((a,s)=>a+s.right,0);
 app.innerHTML=`<section class="hero"><span class="pill">13 種心律・短任務練習</span><h1>看見特徵，判斷心律。</h1><p>每次 5 題，先看波形再作答。答錯也能完成任務，從解析找到下一步。</p><div class="actions"><button id="practice" class="primary">自由練習</button><button id="quiz">測驗挑戰</button></div>${run&&!run.done?'<button id="resume" class="full" style="margin-top:12px">接續未完成練習</button>':''}</section><div class="metrics"><div class="metric"><b>${attempts}</b><span>累計答題</span></div><div class="metric"><b>${attempts?Math.round(right/attempts*100)+'%':'—'}</b><span>累計正確率</span></div><div class="metric"><b>${save.bestStreak}</b><span>最佳連續答對</span></div></div><h2>五個判讀任務</h2><div class="cards">${missions.map(m=>`<button class="mission" data-mission="${m.id}"><b>${m.title}</b><small>${m.desc}</small><span class="best">${save.best[m.id]>=80?'✓ 已通過':save.best[m.id]>0?'再挑戰一次':'開始 5 題任務'}${save.best[m.id]>0?' · 最佳 '+save.best[m.id]+'%':''}</span></button>`).join('')}</div><div class="card"><div class="row"><div><b>錯題修練</b><p class="muted">${save.wrongs.length?save.wrongs.length+' 種心律待複習':'目前沒有待複習心律'}</p></div><button id="wrong" ${!save.wrongs.length?'disabled':''}>只練錯題</button></div></div><p class="muted">進度保存在此裝置的瀏覽器。不同裝置、私密瀏覽或清除網站資料不會共享紀錄。</p>`;
 bind('#practice',()=>start('practice',ids,0,'自由練習'));bind('#quiz',quizSetup);bind('#wrong',()=>start('wrong',save.wrongs,5,'錯題修練'));if($('#resume'))bind('#resume',showQuestion);
 document.querySelectorAll('[data-mission]').forEach(b=>b.onclick=()=>{const m=missions.find(m=>m.id===b.dataset.mission);start('mission',m.ids,5,m.title,m.id);});
}
function quizSetup(){stop();app.innerHTML='<div class="card"><h1>測驗挑戰</h1><p>作答期間只確認已選答案；全部完成後才顯示分數、答案與解析。</p><div class="actions">'+[10,20,30].map(n=>`<button class="primary" data-count="${n}">${n} 題</button>`).join('')+'</div></div>';document.querySelectorAll('[data-count]').forEach(b=>b.onclick=()=>start('quiz',ids,+b.dataset.count,'測驗挑戰'));}
function start(kind,pool,n,title,mission=null){stop();pool=pool.filter(id=>ids.includes(id));if(!pool.length){navigate('report');return;}streak=0;run={kind,pool:[...pool],n,title,mission,deck:deck(pool,n||13,level),index:0,results:[],done:false,demo};showQuestion();}
function showQuestion(){
 stop();view='game';document.querySelectorAll('[data-view]').forEach(b=>b.classList.remove('active'));
 const q=run.deck[run.index],res=run.results[run.index];
 app.innerHTML=`${run.demo?'<div class="demo">教師展示模式 · 不計入學生紀錄</div>':''}<div class="gamehead"><button id="back" aria-label="返回任務基地">返回</button><h1>${run.title}</h1><span class="pill">${run.index+1}${run.n?' / '+run.n:' 題'}</span></div>${run.n?`<div class="progress" role="progressbar" aria-label="答題進度" aria-valuemin="0" aria-valuemax="${run.n}" aria-valuenow="${run.results.length}"><span style="width:${run.results.length/run.n*100}%"></span></div>`:''}${run.demo?`<label>展示心律 <select id="demoRhythm">${allowedRhythms.map(x=>`<option value="${x.id}" ${q.id===x.id?'selected':''}>${x.name}</option>`).join('')}</select></label>`:''}<section class="card"><div class="ecg"><img id="strip" src="${image(q.id)}" alt="待判讀心電圖波形"></div><div class="tools"><button id="play">逐步播放</button><button id="pause" disabled>暫停</button><button id="full">完整圖</button><button id="enlarge">放大檢視</button></div><small>播放是原圖逐步顯示，不代表實際監視器速度；可隨時切回完整圖。</small><div class="guide" aria-label="判讀順序"><span>① 快慢</span><span>② PP／RR</span><span>③ P、QRS、PR</span><span>④ P–QRS</span></div><h2>What is this rhythm?</h2><div class="choices">${q.options.map((id,i)=>`<button class="choice" data-answer="${id}"><span class="letter">${'ABCD'[i]}</span><span>${r(id).name}</span></button>`).join('')}</div><div id="feedback" role="status"></div><div id="nextrow"></div>${run.demo?'<button id="preview" class="full" style="margin-top:12px">教師查看解析</button>':''}</section>`;
 bind('#back',()=>navigate('home'));bind('#enlarge',()=>{$('#zoomImg').src=image(q.id);$('#zoom').showModal();});
 bind('#play',()=>{stop();if(matchMedia('(prefers-reduced-motion: reduce)').matches){notice('已依系統「減少動態」設定保留完整圖。');return;}animation=$('#strip').animate([{clipPath:'inset(0 100% 0 0)'},{clipPath:'inset(0 0% 0 0)'}],{duration:8000,easing:'linear',fill:'forwards'});$('#pause').disabled=false;$('#pause').textContent='暫停';animation.onfinish=()=>{$('#pause').disabled=true;};});
 bind('#pause',()=>{if(!animation)return;if(animation.playState==='paused'){animation.play();$('#pause').textContent='暫停';}else{animation.pause();$('#pause').textContent='繼續';}});
 bind('#full',()=>{stop();$('#pause').disabled=true;});
 document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>answer(b.dataset.answer));
 if(run.demo){$('#demoRhythm').onchange=e=>{run.deck[run.index]=deck([e.target.value],1,level)[0];run.results.splice(run.index);showQuestion();};bind('#preview',()=>{if(!run.results[run.index])answer(q.id);});}
 if(res)feedback(res);
 app.focus({preventScroll:true});window.scrollTo(0,0);
}
function answer(selected){if(run.results[run.index])return;stop();const q=run.deck[run.index],correct=selected===q.id;streak=correct?streak+1:0;
 const res={id:q.id,selected,correct};run.results.push(res);
 if(!run.demo){record(save,q.id,correct,streak);if(run.kind==='wrong'&&correct)save.wrongs=save.wrongs.filter(id=>id!==q.id);persist();}
 feedback(res);
}
function findings(id){return `<ul>${getFindings(id).map(s=>`<li>${s}</li>`).join('')}</ul>`;}
function feedback(res){const quiz=run.kind==='quiz';document.querySelectorAll('[data-answer]').forEach(b=>{b.disabled=true;if(quiz){if(b.dataset.answer===res.selected)b.classList.add('selected');}else{if(b.dataset.answer===res.id)b.classList.add('good');if(b.dataset.answer===res.selected&&!res.correct)b.classList.add('bad');}});
 $('#feedback').innerHTML=quiz?'<p>已記錄您的答案，完成測驗後查看解析。</p>':`<div class="feedback ${res.correct?'':'bad'}"><b>${res.correct?'✓ 答對了！':'✕ 再看一次特徵'}</b><p>正確答案：${r(res.id).name} · ${r(res.id).zh}</p>${findings(res.id)}${!run.demo?`<span class="pill">${res.correct?'+10':'+2'} XP${streak>1?' · 連續 '+streak+' 題答對':''}</span>`:''}</div>`;
 $('#nextrow').innerHTML=`<div class="next-row"><button id="next" class="primary full">${run.n&&run.index===run.n-1?'查看任務結果':'下一題'}</button></div>`;bind('#next',next);
}
function next(){stop();if(run.n&&run.index===run.n-1){complete();return;}run.index++;if(run.index>=run.deck.length)run.deck.push(...deck(run.pool,13,level));showQuestion();}
function complete(){run.done=true;const score=run.results.filter(x=>x.correct).length,accuracy=Math.round(score/run.results.length*100);if(run.mission&&!run.demo){save.best[run.mission]=Math.max(save.best[run.mission]||0,accuracy);persist();}
 const wrongs=[...new Set(run.results.filter(x=>!x.correct).map(x=>x.id))];
 app.innerHTML=`<section class="card"><span class="pill">${run.demo?'教師展示結果':run.title+' · 完成'}</span><h1>${accuracy>=80?'任務達成！':'找到了下一步練習方向'}</h1><div class="points">${score} / ${run.results.length}</div><p>正確率 ${accuracy}%${run.kind==='mission'?' · 通過目標 80%':''}</p><div class="actions"><button class="primary" id="finish">回任務基地</button><button id="repeat">再挑戰一次</button></div>${wrongs.length?'<button id="retrywrong" class="full" style="margin-top:12px">只練這次答錯的心律</button>':''}</section><section class="card"><h2>本次解析回顧</h2>${run.results.map((x,i)=>`<details class="review"><summary>${i+1}. ${x.correct?'✓':'✕'} ${r(x.id).name}${x.correct?'':' · 您選擇 '+r(x.selected).name}</summary><img src="${image(x.id)}" alt="${r(x.id).name} 心電圖">${findings(x.id)}</details>`).join('')}</section>`;
 bind('#finish',()=>navigate('home'));bind('#repeat',()=>start(run.kind,run.pool,run.n,run.title,run.mission));if(wrongs.length)bind('#retrywrong',()=>start('wrong',wrongs,5,'本次錯題修練'));window.scrollTo(0,0);
}
function report(){const seen=Object.values(save.stats).reduce((a,s)=>a+s.seen,0);app.innerHTML=`<h1>學習報告</h1><p class="muted">依實際答題紀錄找出下一步。正確率表示這些模板的作答表現，並非臨床能力認證。</p><div class="card"><div class="row"><b>待複習 ${save.wrongs.length} 種心律</b><button id="reportWrong" ${!save.wrongs.length?'disabled':''}>錯題修練</button></div><p class="muted">${seen?'累計 '+seen+' 次判讀。':'尚未開始，先完成一個 5 題任務。'}</p></div><section class="card">${allowedRhythms.map(x=>{const s=save.stats[x.id],pct=s?.seen?Math.round(s.right/s.seen*100):null;return `<div class="stat"><div><b>${x.name}</b><div class="muted">${x.zh}</div><small>${s?.seen?s.seen+' 次練習 · 答錯 '+s.miss+' 次':'尚未練習'}</small></div><b>${pct===null?'—':pct+'%'}</b><div class="bar"><span style="width:${pct||0}%"></span></div></div>`;}).join('')}</section>`;bind('#reportWrong',()=>start('wrong',save.wrongs,5,'錯題修練'));}
function settings(){app.innerHTML=`<h1>遊戲設定</h1><section class="card"><label for="difficulty"><b>干擾選項難度</b></label><p class="muted">所有難度皆使用同一組 13 張核准模板。</p><select id="difficulty"><option value="beginner">Beginner · 混合選項</option><option value="intermediate">Intermediate · 兩個相似選項</option><option value="advanced">Advanced · 三個相似選項</option></select><p class="muted">難度改變干擾選項的相似程度；波形均沿用核准模板。</p></section><section class="card"><div class="row"><div><b>教師展示模式</b><p class="muted">自由選擇 13 種心律、查看解析，不計入學生紀錄。</p></div><button id="demo" aria-pressed="${demo}">${demo?'已開啟':'已關閉'}</button></div></section><section class="card"><b>紀錄保存在此瀏覽器</b><p class="muted">此版本不收集姓名，也不會將成績上傳。GitHub 與原網站各有獨立的瀏覽器紀錄。</p><button id="reset" class="danger">清除學習紀錄</button></section>`;$('#difficulty').value=level;$('#difficulty').onchange=e=>{level=e.target.value;persist();};bind('#demo',()=>{demo=!demo;run=null;settings();});bind('#reset',()=>{if(confirm('確定清除本瀏覽器的答題、XP 與錯題紀錄？')){save=fresh();run=null;persist();settings();}});}
$('#closeZoom').onclick=()=>$('#zoom').close();$('#zoom').addEventListener('click',e=>{if(e.target===$('#zoom'))$('#zoom').close();});document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>navigate(b.dataset.view));
persist();navigate('home');
